// ─── Public page metadata register ──────────────────────────────────────────
//
// WHY THIS EXISTS
//   index.html carries ONE title and ONE description, and `vercel.json` rewrites
//   every non-API path to that one document. So before this module, every URL on
//   the site — `/`, `/farmer`, and now the corporate pages — presented a crawler
//   with identical metadata. Adding real corporate pages without this would have
//   produced four URLs that search engines are entitled to treat as duplicates
//   of the landing page.
//
//   index.html says so itself: it carries no <link rel="canonical"> because a
//   static one would claim to describe `/farmer` too, and defers the per-page
//   case to "the per-page metadata work". This is that work.
//
// SHAPE OF THE FIX
//   A static map from Page to metadata, plus a thin applier that writes it into
//   the document head. The map is pure data and the decision logic is pure, so
//   the register is testable in the repo's default `environment: 'node'` suite;
//   only `applyPublicPageMetadata` touches the DOM, and it takes the Document as
//   an argument rather than reaching for a global.
//
// THE SAFETY PROPERTY THAT MATTERS MOST
//   Metadata is only ever READ FROM THIS FILE. No caller may pass a title or a
//   description in. That is what makes it structurally impossible for a farm
//   name, a batch id, a buyer's organisation or any other operational record to
//   reach the document head — where it would be read by a crawler, sent in a
//   referrer, and shown in a browser tab and history. A `page` is an enum
//   member; there is no channel through which a record could arrive.

import type { Page } from '../types'

/**
 * The approved production origin.
 *
 * The apex 308-redirects to www, so www is the canonical host — a canonical URL
 * on the apex would point a crawler at a redirect instead of at the page. This
 * is the same constant the crawl-policy files are asserted against, and the
 * sitemap is generated by hand against it.
 */
export const CANONICAL_ORIGIN = 'https://www.ddpbrokerage.com'

/**
 * The metadata model from the search-exposure master plan, section 9 (Phase 4).
 * The plan's field list is the contract; this is that interface verbatim.
 */
export interface PublicPageMetadata {
  title: string
  description: string
  canonicalPath: string
  robots: 'index,follow' | 'noindex,nofollow'
  /**
   * The document language, written into `<html lang>` on the prerendered page.
   *
   * Absent means English, which is what index.html declares and what every page
   * but /de is written in. A wrong `lang` is not cosmetic: it is what a screen
   * reader uses to choose a voice, and what a search engine uses to decide
   * which country's results a page belongs in.
   */
  lang?: 'en' | 'de' | 'cs' | 'th'
  /**
   * The date this page's content was last reviewed, as YYYY-MM-DD.
   *
   * AUTHORED, NEVER DERIVED. It was briefly derived from git — the date of the
   * last commit touching a page's sources — and that had two faults. It said
   * "this file changed", which is not the same claim as "a person checked this
   * page is still true"; and it could not be trusted on a CI host, because
   * `git log -1` in a shallow clone returns the boundary commit rather than
   * failing, reporting files untouched for months as changed that week.
   *
   * This is the ONE place the date lives. The sitemap's <lastmod> reads it, and
   * so does the "last reviewed" line the page itself displays — so a visitor
   * and a search engine cannot be told different things, which is what happened
   * while the shells hardcoded their own copy of it.
   */
  lastReviewed: string
}

/**
 * The register of what may be indexed.
 *
 * Two rules, both load-bearing:
 *
 *   1. `index,follow` appears ONLY on pages that are approved public corporate
 *      information. Everything else in this map is explicitly `noindex,nofollow`
 *      rather than absent, because absence is easy to misread as "not decided
 *      yet" when it needs to read as "decided: not for search".
 *
 *   2. Every `index,follow` entry here must also appear in `public/sitemap.xml`,
 *      and nothing else may. crawlPolicyFiles.test.ts asserts the sitemap side;
 *      publicPageMetadata.test.ts asserts they agree.
 *
 * DESCRIPTIONS are held to 160 characters — the length a result snippet
 * actually shows — and every one is either landing-page copy already approved
 * on `main` or a plain description of what the page contains. None of them
 * asserts a certification, an approval or a compliance status.
 */
const PUBLIC_PAGE_METADATA: Partial<Record<Page, PublicPageMetadata>> = {
  landing: {
    // Retitled for supplier acquisition. "Procurement Intelligence" is owned by
    // market-research publishers and its searchers want reports, not a broker —
    // it described the company to nobody who was looking for it.
    title: 'DDP Brokerage — Buying Thai Cannabis Supply for EU Buyers',
    // Identical to the <meta name="description"> in index.html. The static tag
    // is what a crawler that does not execute JavaScript sees; this entry is
    // what restores the landing description after the visitor navigates to a
    // corporate page and back. They must not drift apart, and
    // publicPageMetadata.test.ts reads index.html to check that they have not.
    description:
      'DDP Brokerage buys from licensed Thai producers for a certified pharmaceutical buyer in Central Europe. Send your documentation as it is — our team reviews it.',
    canonicalPath: '/',
    robots: 'index,follow',
    lastReviewed: '2026-08-08',
  },

  about: {
    title: 'About DDP Brokerage — organizing supplier evidence for buyers',
    description:
      'Who DDP Brokerage is, how supplier documentation is reviewed, and the limits of what the company does and does not assess.',
    canonicalPath: '/about',
    robots: 'index,follow',
    lastReviewed: '2026-08-08',
  },

  governance: {
    title: 'Governance — how DDP Brokerage keeps the record',
    description:
      'The four-state status vocabulary shared by the public site and the console, who is accountable for each clearance, and the limits DDP states plainly.',
    canonicalPath: '/governance',
    robots: 'index,follow',
    lastReviewed: '2026-08-13',
  },

  contact: {
    title: 'Contact DDP Brokerage — Bangkok head office and enquiry channels',
    description:
      'Head office address, telephone number and email channels for DDP Brokerage Co., Ltd., and how licensed suppliers request access.',
    canonicalPath: '/contact',
    robots: 'index,follow',
    lastReviewed: '2026-08-08',
  },

  privacy: {
    title: 'Privacy Policy — DDP Brokerage',
    description:
      'What personal information the DDP Brokerage platform collects, why it is held, who processes it, and how to reach the company about it.',
    canonicalPath: '/privacy',
    robots: 'index,follow',
    lastReviewed: '2026-08-08',
  },

  terms: {
    title: 'Terms of Use — DDP Brokerage',
    description:
      'The conditions for using the DDP Brokerage platform: who may hold access, how information may be relied on, and the limits of the service.',
    canonicalPath: '/terms',
    robots: 'index,follow',
    lastReviewed: '2026-08-08',
  },

  /**
   * The German-language buyer page.
   *
   * WHY GERMAN AND NOT ANOTHER LANGUAGE
   *   The site publishes English and Thai. Thai serves the SUPPLY side — Thai
   *   farms, reached by QR code and WhatsApp. Germany and Czechia are the two
   *   demand-side markets the company names, and neither had any language on
   *   the site. A German buyer searches in German and would not have reached an
   *   English page for any query they were likely to type.
   *
   * WHAT IT MAY SAY
   *   Nothing that is not already published in English on the landing page. The
   *   page is a translation of approved copy — the hero, the four process steps
   *   and BOTH legal notices — and adds no assertion of its own. That rule is
   *   not stylistic: no wording here has been through a compliance review in any
   *   of the six jurisdictions this company operates across, so translation of
   *   language already standing publicly is the only safe construction
   *   available. germanBuyerPage.test.ts asserts the notices are present.
   */
  'de-buyer': {
    title: 'DDP Brokerage — Cannabis-Beschaffung für lizenzierte Einkäufer',
    description:
      'DDP strukturiert Chargenunterlagen, COAs und Preise lizenzierter Produzenten zu klaren Prüfpaketen. Keine Zertifizierung — nur geprüfte Dokumente.',
    canonicalPath: '/de',
    robots: 'index,follow',
    lang: 'de',
    lastReviewed: '2026-08-09',
  },

  /**
   * The Czech-language buyer page.
   *
   * Czechia is the second demand-side market the company names. Smaller than
   * Germany, and reached the same way: a buyer searching in their own language
   * would not have found an English page. Same rule on what it may say — see
   * the /de entry above and pages/public/localisedBuyerContent.ts.
   */
  'cs-buyer': {
    title: 'DDP Brokerage — nákup konopí pro licencované kupující',
    description:
      'DDP strukturuje šaržní záznamy, COA a ceny licencovaných producentů do přehledných podkladů. Žádná certifikace — pouze zkontrolované dokumenty.',
    canonicalPath: '/cs',
    robots: 'index,follow',
    lang: 'cs',
    lastReviewed: '2026-08-09',
  },

  /**
   * The Thai supplier page. INDEXABLE ONLY ONCE A THAI SPEAKER HAS READ IT.
   *
   * Supply acquisition is the commercial focus and this is the page that serves
   * it. It ships noindex because its newly drafted Thai has not been read by a
   * Thai speaker — the audience is licensed operators and their compliance
   * staff, and this audience gives one first impression.
   *
   * Lifting it is a one-line change here plus the hand-written URL list in
   * crawlPolicyFiles.test.ts — two deliberate edits, which is the point.
   */
  'th-supplier': {
    title: 'สมัครเป็นผู้จัดหาสินค้า — DDP Brokerage',
    description:
      'เอกสารที่ผู้ผลิตที่ได้รับใบอนุญาตต้องเตรียมก่อนยื่นคำขอกับ DDP Brokerage: ใบอนุญาต COA เฉพาะแบทช์ และบันทึกแบทช์',
    canonicalPath: '/th/suppliers',
    robots: 'noindex,nofollow',
    lang: 'th',
    lastReviewed: '2026-08-09',
  },

  /**
   * The regulatory-updates hub.
   *
   * INDEXABLE ONLY ONCE ENTRIES EXIST. A hub that lists nothing is a thin page,
   * and publishing one to search engines spends crawl attention on a promise
   * rather than content. regulatoryUpdates.test.ts asserts the rule directly —
   * indexable if and only if at least one entry is published — so the day the
   * first entry lands the suite fails and says to flip this value. That is the
   * same deliberate-human-edit mechanism the sitemap's URL list uses.
   */
  'regulatory-hub': {
    title: 'Regulatory updates — DDP Brokerage',
    description:
      'Notes on regulatory developments affecting licensed cannabis supply. Each entry carries the date it was last verified and the reviewer responsible.',
    canonicalPath: '/regulatory-updates',
    robots: 'noindex,nofollow',
    lastReviewed: '2026-08-09',
  },

  // ── Routable but deliberately NOT indexable ───────────────────────────────
  //
  // /farmer is a real cold-loadable URL — farmers reach it from a QR code and a
  // WhatsApp share — so any external link can point a crawler at it.
  //
  // THIS ENTRY IS THE SECOND OF THREE CONTROLS, NOT THE ONLY ONE.
  //
  // The exclusion used to be undeliverable: robots.txt disallowed /farmer, so a
  // compliant crawler never fetched the page and never read this tag. The two
  // controls stacked instead of composing, and the weaker one won, while an
  // externally linked /farmer could still be indexed as a bare URL.
  //
  // Containment now depends on three things holding together:
  //
  //   1. robots.txt ALLOWS /farmer to be crawled — otherwise 2 and 3 are both
  //      unreachable. Counter-intuitive, and the whole fix.
  //   2. vercel.json returns `X-Robots-Tag: noindex, nofollow` for the /farmer
  //      path. This is the AUTHORITATIVE control: the SPA rewrite serves this
  //      route as a client-rendered document, so a header on the response is
  //      the only exclusion that exists before JavaScript runs.
  //   3. this entry, which puts `noindex,nofollow` in the rendered DOM as
  //      defence in depth for anything that reads the page rather than the
  //      headers.
  //
  // Crawlable is NOT indexable: `robots` stays noindex here, `isIndexable`
  // returns false, and /farmer must never enter the sitemap.
  // publicPageMetadata.test.ts asserts all three conditions as a set.
  //
  // The canonical points at /farmer itself, not "/". Canonicalising onboarding
  // to the landing page would ask a search engine to consolidate them, which is
  // the opposite of keeping them apart.
  'farmer-register': {
    title: 'Supplier registration — DDP Brokerage',
    description: 'Licensed supplier registration for the DDP Brokerage platform.',
    canonicalPath: '/farmer',
    robots: 'noindex,nofollow',
    lastReviewed: '2026-08-08',
  },
}

/**
 * What any page not named in the register gets.
 *
 * Fail-closed: an unknown page is `noindex,nofollow` with a generic title and
 * no description. Every authenticated surface in the application falls here, so
 * adding an admin, farmer or buyer screen can never make one indexable by
 * omission — the only way to publish a page is to add it to the register above
 * and to the sitemap, which is a visible policy edit in a reviewed diff.
 */
const NOT_FOR_SEARCH: PublicPageMetadata = {
  title: 'DDP Brokerage',
  description: '',
  canonicalPath: '/',
  robots: 'noindex,nofollow',
  // Never published, so never reviewed. A real date here would imply a page
  // somebody checked; this is the fall-closed default for everything else.
  lastReviewed: '2026-08-08',
}

/** The metadata for `page`, or the fail-closed default. Pure. */
export function metadataForPage(page: Page): PublicPageMetadata {
  return PUBLIC_PAGE_METADATA[page] ?? NOT_FOR_SEARCH
}

/** The absolute canonical URL for `page`, always on the canonical host. */
export function canonicalUrlFor(page: Page): string {
  return `${CANONICAL_ORIGIN}${metadataForPage(page).canonicalPath}`
}

/**
 * Pages that are the same content in different languages.
 *
 * WHY THIS HAS TO BE DECLARED
 *   Without it, `/` and `/de` are two pages saying the same things in two
 *   languages, and a search engine is entitled to read that as duplication and
 *   pick one. `hreflang` is how you say "these are alternates, serve the right
 *   one to the right reader" instead of leaving it to be guessed.
 *
 *   The declaration must be RECIPROCAL — every page in a group must point at
 *   every other, itself included. A one-way hreflang is ignored outright, which
 *   is the most common way this is got wrong, so the alternates are generated
 *   from one group rather than written per page.
 */
const TRANSLATION_GROUPS: readonly (readonly Page[])[] = [['landing', 'de-buyer', 'cs-buyer']]

export interface LanguageAlternate {
  hreflang: string
  href: string
}

/**
 * The `hreflang` alternates for `page`, or none if it has no translations.
 *
 * `x-default` names the page served to a reader whose language matches nothing
 * in the group. English is the site's own default and the language every other
 * public page is written in.
 */
export function languageAlternatesFor(page: Page): LanguageAlternate[] {
  const group = TRANSLATION_GROUPS.find((pages) => pages.includes(page))
  if (!group) return []

  const alternates = group.map((member) => ({
    hreflang: metadataForPage(member).lang ?? 'en',
    href: canonicalUrlFor(member),
  }))

  const english = alternates.find((alternate) => alternate.hreflang === 'en')
  return english ? [...alternates, { hreflang: 'x-default', href: english.href }] : alternates
}

/** True when the register approves `page` for public search indexing. */
export function isIndexable(page: Page): boolean {
  return metadataForPage(page).robots === 'index,follow'
}

/** Every page the register approves for indexing, in declaration order. */
export function indexablePages(): Page[] {
  return (Object.keys(PUBLIC_PAGE_METADATA) as Page[]).filter(isIndexable)
}

/** The absolute URLs the sitemap is allowed to contain, and no others. */
export function approvedSitemapUrls(): string[] {
  return indexablePages().map(canonicalUrlFor)
}

/**
 * Writes the register's entry for `page` into the document head.
 *
 * Takes the Document rather than reading the global so it can be driven in a
 * test without a browser, and so it is a no-op-by-omission rather than a crash
 * in any non-DOM context.
 *
 * Every tag it manages is REPLACED on every call, never merely added. That is
 * the "stale metadata must not survive navigation" requirement: the failure
 * this prevents is a visitor going landing → privacy → back and leaving the
 * privacy canonical in place, so the landing page tells a crawler that its
 * canonical URL is /privacy. An empty description removes the tag outright
 * rather than publishing an empty one.
 */
export function applyPublicPageMetadata(doc: Document, page: Page): void {
  const meta = metadataForPage(page)

  doc.title = meta.title

  setMetaByName(doc, 'description', meta.description)
  setMetaByName(doc, 'robots', meta.robots)
  setCanonicalLink(doc, `${CANONICAL_ORIGIN}${meta.canonicalPath}`)
}

/** Creates, updates or removes `<meta name="…" content="…">`. */
function setMetaByName(doc: Document, name: string, content: string): void {
  const selector = `meta[name="${name}"]`
  const existing = doc.head.querySelector(selector)

  if (!content) {
    existing?.remove()
    return
  }

  const tag = existing ?? doc.head.appendChild(doc.createElement('meta'))
  tag.setAttribute('name', name)
  tag.setAttribute('content', content)
}

/** Creates or updates the single `<link rel="canonical">`. */
function setCanonicalLink(doc: Document, href: string): void {
  const existing = doc.head.querySelector('link[rel="canonical"]')
  const tag = existing ?? doc.head.appendChild(doc.createElement('link'))
  tag.setAttribute('rel', 'canonical')
  tag.setAttribute('href', href)
}
