// ─── Public page metadata register ──────────────────────────────────────────
//
// WHY THIS EXISTS
//   index.html carries ONE title and ONE description, and `vercel.json` rewrites
//   every non-API path to that one document. So before this module, every URL on
//   the site — `/`, `/farmer`, and now the corporate pages — presented a crawler
//   with identical metadata. Adding real corporate pages without this would have
//   produced four URLs that search engines are entitled to treat as duplicates
//   of the landing page.
//
//   index.html says so itself: it carries no <link rel="canonical"> because a
//   static one would claim to describe `/farmer` too, and defers the per-page
//   case to "the per-page metadata work". This is that work.
//
// SHAPE OF THE FIX
//   A static map from Page to metadata, plus a thin applier that writes it into
//   the document head. The map is pure data and the decision logic is pure, so
//   the register is testable in the repo's default `environment: 'node'` suite;
//   only `applyPublicPageMetadata` touches the DOM, and it takes the Document as
//   an argument rather than reaching for a global.
//
// THE SAFETY PROPERTY THAT MATTERS MOST
//   Metadata is only ever READ FROM THIS FILE. No caller may pass a title or a
//   description in. That is what makes it structurally impossible for a farm
//   name, a batch id, a buyer's organisation or any other operational record to
//   reach the document head — where it would be read by a crawler, sent in a
//   referrer, and shown in a browser tab and history. A `page` is an enum
//   member; there is no channel through which a record could arrive.

import type { Page } from '../types'

/**
 * The approved production origin.
 *
 * The apex 308-redirects to www, so www is the canonical host — a canonical URL
 * on the apex would point a crawler at a redirect instead of at the page. This
 * is the same constant the crawl-policy files are asserted against, and the
 * sitemap is generated by hand against it.
 */
export const CANONICAL_ORIGIN = 'https://www.ddpbrokerage.com'

/**
 * The metadata model from the search-exposure master plan, section 9 (Phase 4).
 * The plan's field list is the contract; this is that interface verbatim.
 */
export interface PublicPageMetadata {
  title: string
  description: string
  canonicalPath: string
  robots: 'index,follow' | 'noindex,nofollow'
}

/**
 * The register of what may be indexed.
 *
 * Two rules, both load-bearing:
 *
 *   1. `index,follow` appears ONLY on pages that are approved public corporate
 *      information. Everything else in this map is explicitly `noindex,nofollow`
 *      rather than absent, because absence is easy to misread as "not decided
 *      yet" when it needs to read as "decided: not for search".
 *
 *   2. Every `index,follow` entry here must also appear in `public/sitemap.xml`,
 *      and nothing else may. crawlPolicyFiles.test.ts asserts the sitemap side;
 *      publicPageMetadata.test.ts asserts they agree.
 *
 * DESCRIPTIONS are held to 160 characters — the length a result snippet
 * actually shows — and every one is either landing-page copy already approved
 * on `main` or a plain description of what the page contains. None of them
 * asserts a certification, an approval or a compliance status.
 */
const PUBLIC_PAGE_METADATA: Partial<Record<Page, PublicPageMetadata>> = {
  landing: {
    title: 'DDP Brokerage — Procurement Intelligence',
    // Identical to the <meta name="description"> in index.html. The static tag
    // is what a crawler that does not execute JavaScript sees; this entry is
    // what restores the landing description after the visitor navigates to a
    // corporate page and back. They must not drift apart, and
    // publicPageMetadata.test.ts reads index.html to check that they have not.
    description:
      'DDP turns farm stock, batch records, COAs, and pricing into clear review packs for serious buyers.',
    canonicalPath: '/',
    robots: 'index,follow',
  },

  about: {
    title: 'About DDP Brokerage — organizing supplier evidence for buyers',
    description:
      'Who DDP Brokerage is, how supplier documentation is reviewed, and the limits of what the company does and does not assess.',
    canonicalPath: '/about',
    robots: 'index,follow',
  },

  contact: {
    title: 'Contact DDP Brokerage — Bangkok head office and enquiry channels',
    description:
      'Head office address, telephone number and email channels for DDP Brokerage Co., Ltd., and how licensed suppliers request access.',
    canonicalPath: '/contact',
    robots: 'index,follow',
  },

  privacy: {
    title: 'Privacy Policy — DDP Brokerage',
    description:
      'What personal information the DDP Brokerage platform collects, why it is held, who processes it, and how to reach the company about it.',
    canonicalPath: '/privacy',
    robots: 'index,follow',
  },

  terms: {
    title: 'Terms of Use — DDP Brokerage',
    description:
      'The conditions for using the DDP Brokerage platform: who may hold access, how information may be relied on, and the limits of the service.',
    canonicalPath: '/terms',
    robots: 'index,follow',
  },

  // ── Routable but deliberately NOT indexable ───────────────────────────────
  //
  // /farmer is a real cold-loadable URL — farmers reach it from a QR code and a
  // WhatsApp share — so any external link can point a crawler at it.
  //
  // THIS ENTRY IS THE SECOND OF THREE CONTROLS, NOT THE ONLY ONE.
  //
  // The exclusion used to be undeliverable: robots.txt disallowed /farmer, so a
  // compliant crawler never fetched the page and never read this tag. The two
  // controls stacked instead of composing, and the weaker one won, while an
  // externally linked /farmer could still be indexed as a bare URL.
  //
  // Containment now depends on three things holding together:
  //
  //   1. robots.txt ALLOWS /farmer to be crawled — otherwise 2 and 3 are both
  //      unreachable. Counter-intuitive, and the whole fix.
  //   2. vercel.json returns `X-Robots-Tag: noindex, nofollow` for the /farmer
  //      path. This is the AUTHORITATIVE control: the SPA rewrite serves this
  //      route as a client-rendered document, so a header on the response is
  //      the only exclusion that exists before JavaScript runs.
  //   3. this entry, which puts `noindex,nofollow` in the rendered DOM as
  //      defence in depth for anything that reads the page rather than the
  //      headers.
  //
  // Crawlable is NOT indexable: `robots` stays noindex here, `isIndexable`
  // returns false, and /farmer must never enter the sitemap.
  // publicPageMetadata.test.ts asserts all three conditions as a set.
  //
  // The canonical points at /farmer itself, not "/". Canonicalising onboarding
  // to the landing page would ask a search engine to consolidate them, which is
  // the opposite of keeping them apart.
  'farmer-register': {
    title: 'Supplier registration — DDP Brokerage',
    description: 'Licensed supplier registration for the DDP Brokerage platform.',
    canonicalPath: '/farmer',
    robots: 'noindex,nofollow',
  },
}

/**
 * What any page not named in the register gets.
 *
 * Fail-closed: an unknown page is `noindex,nofollow` with a generic title and
 * no description. Every authenticated surface in the application falls here, so
 * adding an admin, farmer or buyer screen can never make one indexable by
 * omission — the only way to publish a page is to add it to the register above
 * and to the sitemap, which is a visible policy edit in a reviewed diff.
 */
const NOT_FOR_SEARCH: PublicPageMetadata = {
  title: 'DDP Brokerage',
  description: '',
  canonicalPath: '/',
  robots: 'noindex,nofollow',
}

/** The metadata for `page`, or the fail-closed default. Pure. */
export function metadataForPage(page: Page): PublicPageMetadata {
  return PUBLIC_PAGE_METADATA[page] ?? NOT_FOR_SEARCH
}

/** The absolute canonical URL for `page`, always on the canonical host. */
export function canonicalUrlFor(page: Page): string {
  return `${CANONICAL_ORIGIN}${metadataForPage(page).canonicalPath}`
}

/** True when the register approves `page` for public search indexing. */
export function isIndexable(page: Page): boolean {
  return metadataForPage(page).robots === 'index,follow'
}

/** Every page the register approves for indexing, in declaration order. */
export function indexablePages(): Page[] {
  return (Object.keys(PUBLIC_PAGE_METADATA) as Page[]).filter(isIndexable)
}

/** The absolute URLs the sitemap is allowed to contain, and no others. */
export function approvedSitemapUrls(): string[] {
  return indexablePages().map(canonicalUrlFor)
}

/**
 * Writes the register's entry for `page` into the document head.
 *
 * Takes the Document rather than reading the global so it can be driven in a
 * test without a browser, and so it is a no-op-by-omission rather than a crash
 * in any non-DOM context.
 *
 * Every tag it manages is REPLACED on every call, never merely added. That is
 * the "stale metadata must not survive navigation" requirement: the failure
 * this prevents is a visitor going landing → privacy → back and leaving the
 * privacy canonical in place, so the landing page tells a crawler that its
 * canonical URL is /privacy. An empty description removes the tag outright
 * rather than publishing an empty one.
 */
export function applyPublicPageMetadata(doc: Document, page: Page): void {
  const meta = metadataForPage(page)

  doc.title = meta.title

  setMetaByName(doc, 'description', meta.description)
  setMetaByName(doc, 'robots', meta.robots)
  setCanonicalLink(doc, `${CANONICAL_ORIGIN}${meta.canonicalPath}`)
}

/** Creates, updates or removes `<meta name="…" content="…">`. */
function setMetaByName(doc: Document, name: string, content: string): void {
  const selector = `meta[name="${name}"]`
  const existing = doc.head.querySelector(selector)

  if (!content) {
    existing?.remove()
    return
  }

  const tag = existing ?? doc.head.appendChild(doc.createElement('meta'))
  tag.setAttribute('name', name)
  tag.setAttribute('content', content)
}

/** Creates or updates the single `<link rel="canonical">`. */
function setCanonicalLink(doc: Document, href: string): void {
  const existing = doc.head.querySelector('link[rel="canonical"]')
  const tag = existing ?? doc.head.appendChild(doc.createElement('link'))
  tag.setAttribute('rel', 'canonical')
  tag.setAttribute('href', href)
}
