import type { ComplianceRule, ComplianceRuleStatus, FarmProfile, InventoryItem } from '../types'

// Shared, minimal-but-valid fixture factories for compliance-logic tests.
// Every field is populated so tests only need to override what's relevant
// to the behaviour under test.

export function makeRule(overrides: Partial<ComplianceRule> & { status: ComplianceRuleStatus }): ComplianceRule {
  return {
    id: `rule-${overrides.ruleCode ?? 'TEST_RULE'}-${overrides.status}`,
    ruleCode: 'TEST_RULE',
    title: 'Test rule',
    description: 'A rule used only in tests.',
    jurisdiction: null,
    entityType: 'batch',
    severity: 'high',
    isBlocking: true,
    sourceLegalUpdateId: null,
    approvedBy: null,
    approvedAt: null,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    ...overrides,
  }
}

export function makeFarm(overrides: Partial<FarmProfile> = {}): FarmProfile {
  return {
    id: 'farm-1',
    status: 'Approved',
    submittedAt: '2026-01-01T00:00:00.000Z',
    completionPct: 100,
    legalBusinessName: 'Test Farm Co Ltd',
    tradingName: 'Test Farm',
    registrationNumber: '',
    taxNumber: '',
    dateEstablished: '',
    province: '',
    district: '',
    gpsCoordinates: '',
    registeredAddress: '',
    operationalAddress: '',
    website: '',
    facebook: '',
    lineId: '',
    whatsapp: '',
    email: '',
    primaryContact: '',
    position: '',
    mobileNumber: '',
    secondaryContact: '',
    emergencyContact: '',
    ownerName: '',
    nationality: '',
    ownershipPct: '',
    additionalShareholders: '',
    ownershipBreakdown: '',
    ultimateBeneficialOwners: '',
    parentCompany: '',
    subsidiaries: '',
    foreignInvestors: '',
    strategicPartners: '',
    exportPartners: '',
    cultivationLicence: '',
    processingLicence: '',
    manufacturingLicence: '',
    researchLicence: '',
    medicalCannabisLicence: '',
    exportLicence: '',
    importLicence: '',
    gmpCert: '',
    gapCert: '',
    gacpCert: '',
    picsCert: '',
    organicCert: '',
    isoCerts: '',
    otherCerts: '',
    documentExpiry: '',
    farmType: '',
    totalLandArea: '',
    cultivationArea: '',
    floweringArea: '',
    nurseryArea: '',
    motherPlantArea: '',
    processingArea: '',
    dryingArea: '',
    storageArea: '',
    securityArea: '',
    expansionCapacity: '',
    facilityPhotoUrl: '',
    activeRooms: '',
    harvestsPerYear: '',
    avgYieldPerHarvest: '',
    annualCapacity: '',
    currentInventory: '',
    projectedInventory: '',
    productionUtilisation: '',
    maxProductionCapacity: '',
    cultivationMethod: '',
    fertiliserProgram: '',
    nutrientBrands: '',
    pestManagement: '',
    ipmProcedures: '',
    waterSource: '',
    waterTestingFrequency: '',
    waterAnalysisFile: '',
    mainStrains: '',
    breeder: '',
    geneticLineage: '',
    typicalThc: '',
    typicalCbd: '',
    dominantTerpenes: '',
    harvestCycle: '',
    yieldPerSqm: '',
    qtyAvailableNow: '',
    qtyAvailable30: '',
    qtyAvailable60: '',
    qtyAvailable90: '',
    qtyAvailable180: '',
    productPhotoUrl: '',
    coaFiles: '',
    heavyMetalsTested: '',
    pesticidesTested: '',
    mycotoxinsTested: '',
    microbiologyTested: '',
    waterActivityTested: '',
    batchTrackingSystem: '',
    seedToSaleSystem: '',
    sopsAvailable: '',
    recallProcedure: '',
    wasteDisposal: '',
    employeeTraining: '',
    securityProtocols: '',
    visitorProcedures: '',
    incidentReporting: '',
    capaProgram: '',
    internalAudits: '',
    externalAudits: '',
    suppliedEU: '',
    suppliedPharma: '',
    suppliedGMPProcessors: '',
    existingSopLibrary: '',
    existingQA: '',
    existingQC: '',
    qualifiedPerson: '',
    stabilityProgram: '',
    changeControl: '',
    deviationProcedures: '',
    riskManagement: '',
    documentationControl: '',
    countriesExported: '',
    freightProviders: '',
    customsBrokers: '',
    incotermsFamiliarity: '',
    packagingStandards: '',
    labellingStandards: '',
    shippingCapacity: '',
    interestedExclusive: '',
    interestedNonExclusive: '',
    interestedEUGMP: '',
    interestedLongTerm: '',
    interestedJV: '',
    monthlyReportingAgreement: '',
    scoreCompliance: 0,
    scoreDocumentation: 0,
    scoreFacilityQuality: 0,
    scoreProductQuality: 0,
    scoreExportReadiness: 0,
    scoreReliability: 0,
    scoreCommunication: 0,
    scoreScalability: 0,
    scoreGMPReadiness: 0,
    ...overrides,
  }
}

export function makeInventoryItem(overrides: Partial<InventoryItem> = {}): InventoryItem {
  return {
    id: 'batch-1',
    farmerName: 'Test Farmer',
    farmName: 'Test Farm',
    farmId: 'farm-1',
    location: '',
    productName: 'Test Product',
    quantityKg: 10,
    harvestDate: '2026-01-01',
    cureDate: '2026-01-10',
    batchNumber: 'BATCH-001',
    thcPct: 0,
    cbdPct: 0,
    moisturePct: 0,
    waterActivity: '',
    qualityGrade: '',
    pricePerKg: 0,
    certFileName: '',
    photoUrl: '',
    storageConditions: '',
    notes: '',
    status: 'Approved',
    submittedAt: '2026-01-01T00:00:00.000Z',
    ...overrides,
  }
}
