-- ============================================================================
-- FILE C: SEED_CLEAN_BASELINE.sql
-- Date: 2026-06-30
--
-- Creates a minimal, clean demo baseline after RESET_B_DEMO_DATA.sql.
--
-- What this creates:
--   • One demo farm — "DDP Demo Farm Co., Ltd." with realistic but
--     clearly fake registration details (no real license numbers).
--   • One farm_profile row with minimal JSON fields.
--   • One farm_membership linking the demo farm to an existing farmer
--     auth user (identified by email — see STEP 2 below).
--   • One pending inventory batch — clean state, no fake compliance claims.
--
-- What this does NOT create:
--   • No fake COA test results or lab reports.
--   • No ddp_scores (admin assigns those after review).
--   • No risk_flags (admin assigns those after review).
--   • No documents (farmer uploads those via the app).
--   • No status_history (generated by real app actions).
--   • No auth.users (use Supabase Auth to create the farmer first).
--
-- BEFORE RUNNING:
--   1. Confirm the reset (File B) has been applied successfully.
--   2. Confirm the farmer auth user already exists in auth.users.
--      Replace 'demo-farmer@example.com' below with the actual email.
--      If no farmer user exists yet, create one via Supabase Auth first,
--      then run this script.
--   3. The admin account must exist (File B preserves it).
--
-- STABLE IDs:
--   The demo farm uses a fixed UUID so this script is idempotent
--   (ON CONFLICT DO NOTHING). Re-running it is safe.
-- ============================================================================

BEGIN;

-- ── Stable UUIDs used in this seed ──────────────────────────────────────────
-- Demo farm:          ddp00000-0000-0000-0000-000000000001
-- Demo batch:         ddp00000-0000-0000-0000-000000000002
-- These are easily recognisable and will not collide with gen_random_uuid().


-- ============================================================================
-- STEP 1: Create the demo farm
-- ============================================================================
INSERT INTO public.farms (
  id,
  farm_name,
  legal_business_name,
  trading_name,
  province,
  district,
  gps_coordinates,
  primary_contact,
  mobile_number,
  email,
  status,
  completion_percentage,
  compliance_status,
  export_readiness,
  risk_level,
  partner_tier,
  created_at,
  updated_at
)
VALUES (
  'ddp00000-0000-0000-0000-000000000001',
  'DDP Demo Farm',
  'DDP Demo Farm Co., Ltd.',
  'Demo Farm',
  'Chiang Mai',
  'Mae Rim',
  '18.9061° N, 98.8598° E',
  'Demo Owner',
  '+66-00-000-0000',
  'demo-farmer@example.com',  -- UPDATE to match the actual farmer email
  'Pending Review',
  25,
  'Incomplete',
  'Not Ready',
  'low',
  'Unrated',
  NOW(),
  NOW()
)
ON CONFLICT (id) DO NOTHING;


-- ============================================================================
-- STEP 2: Create the farm_profile (minimal JSON skeleton)
-- ============================================================================
INSERT INTO public.farm_profiles (
  farm_id,
  business_info,
  ownership,
  licenses,
  facility,
  cultivation,
  strains,
  lab_testing,
  export_readiness_data,
  monthly_reporting,
  created_at,
  updated_at
)
SELECT
  'ddp00000-0000-0000-0000-000000000001',
  '{"legalBusinessName":"DDP Demo Farm Co., Ltd.","province":"Chiang Mai"}'::jsonb,
  '{}'::jsonb,
  '{}'::jsonb,
  '{}'::jsonb,
  '{}'::jsonb,
  '{}'::jsonb,
  '{}'::jsonb,
  '{}'::jsonb,
  '{}'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.farm_profiles
  WHERE farm_id = 'ddp00000-0000-0000-0000-000000000001'
);


-- ============================================================================
-- STEP 3: Link the farmer auth user to the demo farm
--
-- Replace 'demo-farmer@example.com' with the real farmer email.
-- If no farmer user exists yet, skip this step and add the membership
-- manually in the Supabase dashboard or via the app sign-up flow.
-- ============================================================================
INSERT INTO public.farm_memberships (farm_id, user_id, role)
SELECT
  'ddp00000-0000-0000-0000-000000000001',
  p.id,
  'owner'
FROM public.profiles p
WHERE p.email = 'demo-farmer@example.com'   -- UPDATE THIS EMAIL
  AND p.role  = 'farmer'
ON CONFLICT (farm_id, user_id) DO NOTHING;


-- ============================================================================
-- STEP 4: One minimal pending inventory batch
-- No THC/CBD claims, no COA, no quality grade — clean starting state.
-- ============================================================================
INSERT INTO public.inventory_batches (
  id,
  farm_id,
  product_name,
  strain,
  location,
  quantity_kg,
  harvest_date,
  batch_number,
  status,
  notes,
  created_at,
  updated_at
)
VALUES (
  'ddp00000-0000-0000-0000-000000000002',
  'ddp00000-0000-0000-0000-000000000001',
  'Dried Flower',
  'Demo Strain',
  'Storage Room A',
  10.0,
  TO_CHAR(NOW() - INTERVAL '30 days', 'YYYY-MM-DD'),
  'DEMO-BATCH-001',
  'Submitted',        -- initial farmer-submitted state
  'Demo batch — awaiting COA and review.',
  NOW(),
  NOW()
)
ON CONFLICT (id) DO NOTHING;


-- ── Verify seed landed correctly ─────────────────────────────────────────────
SELECT
  f.id            AS farm_id,
  f.farm_name,
  f.status,
  p.email         AS linked_farmer_email,
  fm.role         AS membership_role,
  ib.product_name AS batch_name,
  ib.status       AS batch_status
FROM public.farms f
LEFT JOIN public.farm_memberships fm ON fm.farm_id = f.id
LEFT JOIN public.profiles p          ON p.id = fm.user_id
LEFT JOIN public.inventory_batches ib ON ib.farm_id = f.id
WHERE f.id = 'ddp00000-0000-0000-0000-000000000001';

COMMIT;
